/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-09-06 13:50:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class forecast_005fgraph_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1630931132125L));
    _jspx_dependants.put("jar:file:/D:/EZEN08/boyeon/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring_ilchooL/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/D:/EZEN08/boyeon/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring_ilchooL/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/D:/EZEN08/boyeon/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring_ilchooL/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<body>\r\n");
      out.write("   <div id=\"forecast_box\" class=\"container\">\r\n");
      out.write("      <div id=\"forecast_title\" style=\"text-align: center; height:50px;\">\r\n");
      out.write("         <h1>FORECAST</h1>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"forecast_graph\" class=\"forecast row\">\r\n");
      out.write("         <div id=\"pm10Chart\" class=\"forecast_chart_container col-md-4 col-xs-4\" style=\"height: 46% !important;\">\r\n");
      out.write("            </div>\r\n");
      out.write("         <div id=\"pm25Chart\" class=\"forecast_chart_container col-md-4 col-xs-4\" style=\"height: 46% !important;\">\r\n");
      out.write("            </div>\r\n");
      out.write("         <div id=\"ptyChart\" class=\"forecast_chart_container col-md-4 col-xs-4\" style=\"height: 46% !important;\">\r\n");
      out.write("            </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"nonbox\" style=\"height: 60px;\"></div>\r\n");
      out.write("\r\n");
      out.write("      <div id=\"forecast_graph2\" class=\"forecast row\">\r\n");
      out.write("         <div class=\"forecast_chart_container col-md-6 col-xs-12\" style=\"margin-bottom:30px\">\r\n");
      out.write("            <canvas id=\"tmxChart\"></canvas>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"forecast_chart_container col-md-6 col-xs-12\" style=\"margin-bottom:60px\">\r\n");
      out.write("            <canvas id=\"tmnChart\"></canvas>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   <script src=\"//cdn.amcharts.com/lib/4/core.js\"></script>\r\n");
      out.write("   <script src=\"//cdn.amcharts.com/lib/4/charts.js\"></script>\r\n");
      out.write("   <script src=\"//cdn.amcharts.com/lib/4/themes/animated.js\"></script>\r\n");
      out.write("   <script src=\"https://cdn.amcharts.com/lib/4/themes/frozen.js\"></script>\r\n");
      out.write("   <script src=\"//cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js\"></script>\r\n");
      out.write("   <script>\r\n");
      out.write("      \r\n");
      out.write("      let ptydata = [{weather:\"Sunny\", value:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sunny}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("}, {weather:\"Rainy\", value:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rainy}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("}, {weather:\"Snow\", value:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${snow}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("}, {weather:\"Shower\", value:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shower}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("}]\r\n");
      out.write("      let pm10data = [{pm10:\"great\", value:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pm10_great}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("}, {pm10:\"good\", value:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pm10_good}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("}, {pm10:\"bad\", value:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pm10_bad}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("}, {pm10:\"worst\", value:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pm10_worst}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("}]\r\n");
      out.write("      let pm25data = [{pm25:\"great\", value:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pm25_great}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("}, {pm25:\"good\", value:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pm25_good}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("}, {pm25:\"bad\", value:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pm25_bad}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("}, {pm25:\"worst\", value:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pm25_worst}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("}]\r\n");
      out.write("      \r\n");
      out.write("      let tmxdata =[");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmx_data9}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmx_data8}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmx_data7}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmx_data6}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmx_data5}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmx_data4}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmx_data3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmx_data2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmx_data1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmx_data0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("]\r\n");
      out.write("      let tmndata =[");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmn_data9}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmn_data8}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmn_data7}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmn_data6}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmn_data5}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmn_data4}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmn_data3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmn_data2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmn_data1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmn_data0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("]\r\n");
      out.write("      let daydata =[");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${day_data9}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${day_data8}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${day_data7}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${day_data6}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${day_data5}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${day_data4}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${day_data3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${day_data2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${day_data1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${day_data0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("]\r\n");
      out.write("      \r\n");
      out.write("      var tmx = document.getElementById(\"tmxChart\").getContext('2d');\r\n");
      out.write("      var tmn = document.getElementById(\"tmnChart\").getContext('2d');\r\n");
      out.write("      \r\n");
      out.write("      /** \r\n");
      out.write("      * Doughnut Chart\r\n");
      out.write("      */\r\n");
      out.write("      \r\n");
      out.write("      //---미세먼지 데이터 시각화---\r\n");
      out.write("       am4core.ready(function() {\r\n");
      out.write("         \r\n");
      out.write("         //테마 적용,로고 삭제\r\n");
      out.write("         am4core.addLicense(\"ch-custom-attribution\");\r\n");
      out.write("         am4core.useTheme(am4themes_animated);\r\n");
      out.write("\r\n");
      out.write("         var chart_pm10 = am4core.create(\"pm10Chart\", am4charts.PieChart);\r\n");
      out.write("         chart_pm10.hiddenState.properties.opacity = 0; \r\n");
      out.write("         chart_pm10.fontSize=11;\r\n");
      out.write("         chart_pm10.data = pm10data;\r\n");
      out.write("         chart_pm10.radius = am4core.percent(70);\r\n");
      out.write("         chart_pm10.innerRadius = am4core.percent(50);\r\n");
      out.write("         chart_pm10.startAngle = 150; \r\n");
      out.write("         chart_pm10.endAngle = 390;   \r\n");
      out.write("\r\n");
      out.write("         chart_pm10.legend = new am4charts.Legend();\r\n");
      out.write("         \r\n");
      out.write("         var series_pm10 = chart_pm10.series.push(new am4charts.PieSeries());\r\n");
      out.write("         series_pm10.dataFields.value = \"value\";\r\n");
      out.write("         series_pm10.dataFields.category = \"pm10\";\r\n");
      out.write("         series_pm10.labels.template.disabled = true;\r\n");
      out.write("         series_pm10.ticks.template.disabled = true;\r\n");
      out.write("         \r\n");
      out.write("         series_pm10.slices.template.cornerRadius = 10;\r\n");
      out.write("         series_pm10.slices.template.innerCornerRadius = 7;\r\n");
      out.write("         series_pm10.slices.template.draggable = false;\r\n");
      out.write("         series_pm10.slices.template.inert = false;\r\n");
      out.write("         series_pm10.alignLabels = false;\r\n");
      out.write("         \r\n");
      out.write("         series_pm10.hiddenState.properties.startAngle = 90;\r\n");
      out.write("         series_pm10.hiddenState.properties.endAngle = 90;\r\n");
      out.write("         \r\n");
      out.write("         var label_pm10 = chart_pm10.seriesContainer.createChild(am4core.Label);\r\n");
      out.write("         label_pm10.textAlign = \"middle\";\r\n");
      out.write("         label_pm10.horizontalCenter = \"middle\";\r\n");
      out.write("         label_pm10.verticalCenter = \"middle\";\r\n");
      out.write("         label_pm10.adapter.add(\"text\", function(text, target){\r\n");
      out.write("           return \"[font-size:1.1em]한달 간[/]\\n[bold font-size:1.3em]미세먼지[/]\";\r\n");
      out.write("         })\r\n");
      out.write("         });\r\n");
      out.write("\r\n");
      out.write("       //---초미세먼지 데이터 시각화---\r\n");
      out.write("       am4core.ready(function() {\r\n");
      out.write("          \r\n");
      out.write("         am4core.unuseAllThemes();\r\n");
      out.write("\r\n");
      out.write("         am4core.addLicense(\"ch-custom-attribution\");\r\n");
      out.write("         am4core.useTheme(am4themes_animated);\r\n");
      out.write("         am4core.useTheme(am4themes_frozen);\r\n");
      out.write("\r\n");
      out.write("         var chart_pm25 = am4core.create(\"pm25Chart\", am4charts.PieChart);\r\n");
      out.write("         chart_pm25.hiddenState.properties.opacity = 0; \r\n");
      out.write("         chart_pm25.fontSize=11;\r\n");
      out.write("         chart_pm25.data = pm25data;\r\n");
      out.write("         chart_pm25.radius = am4core.percent(70);\r\n");
      out.write("         chart_pm25.innerRadius = am4core.percent(50);\r\n");
      out.write("         chart_pm25.startAngle = 150; \r\n");
      out.write("         chart_pm25.endAngle = 390;      \r\n");
      out.write("\r\n");
      out.write("         chart_pm25.legend = new am4charts.Legend();\r\n");
      out.write("         \r\n");
      out.write("         var series_pm25 = chart_pm25.series.push(new am4charts.PieSeries());\r\n");
      out.write("         series_pm25.dataFields.value = \"value\";\r\n");
      out.write("         series_pm25.dataFields.category = \"pm25\";\r\n");
      out.write("         series_pm25.labels.template.disabled = true;\r\n");
      out.write("         series_pm25.ticks.template.disabled = true;\r\n");
      out.write("         \r\n");
      out.write("         series_pm25.slices.template.cornerRadius = 10;\r\n");
      out.write("         series_pm25.slices.template.innerCornerRadius = 7;\r\n");
      out.write("         series_pm25.slices.template.draggable = false;\r\n");
      out.write("         series_pm25.slices.template.inert = false;\r\n");
      out.write("         series_pm25.alignLabels = false;\r\n");
      out.write("         \r\n");
      out.write("         series_pm25.hiddenState.properties.startAngle = 90;\r\n");
      out.write("         series_pm25.hiddenState.properties.endAngle = 90;\r\n");
      out.write("         \r\n");
      out.write("         var label_pm25 = chart_pm25.seriesContainer.createChild(am4core.Label);\r\n");
      out.write("         label_pm25.textAlign = \"middle\";\r\n");
      out.write("         label_pm25.horizontalCenter = \"middle\";\r\n");
      out.write("         label_pm25.verticalCenter = \"middle\";\r\n");
      out.write("         label_pm25.adapter.add(\"text\", function(text, target){\r\n");
      out.write("           return \"[font-size:1.1em]한달 간[/]\\n[bold font-size:1.3em]초미세먼지[/]\";\r\n");
      out.write("         })\r\n");
      out.write("         }); \r\n");
      out.write("       \r\n");
      out.write("       //---강수확률 데이터 시각화---\r\n");
      out.write("      am4core.ready(function() {\r\n");
      out.write("         \r\n");
      out.write("         am4core.unuseAllThemes();\r\n");
      out.write("         \r\n");
      out.write("         am4core.addLicense(\"ch-custom-attribution\");\r\n");
      out.write("         am4core.useTheme(am4themes_animated);\r\n");
      out.write("\r\n");
      out.write("         var chart_pty = am4core.create(\"ptyChart\", am4charts.PieChart);\r\n");
      out.write("         chart_pty.hiddenState.properties.opacity = 0; \r\n");
      out.write("         chart_pty.fontSize=11;\r\n");
      out.write("         chart_pty.data = ptydata;\r\n");
      out.write("         chart_pty.radius = am4core.percent(70);\r\n");
      out.write("         chart_pty.innerRadius = am4core.percent(50);\r\n");
      out.write("         chart_pty.startAngle = 150; \r\n");
      out.write("         chart_pty.endAngle = 390;      \r\n");
      out.write("\r\n");
      out.write("         chart_pty.legend = new am4charts.Legend();\r\n");
      out.write("         \r\n");
      out.write("         var series_pty = chart_pty.series.push(new am4charts.PieSeries());\r\n");
      out.write("         series_pty.dataFields.value = \"value\";\r\n");
      out.write("         series_pty.dataFields.category = \"weather\";\r\n");
      out.write("         series_pty.labels.template.disabled = true;\r\n");
      out.write("         series_pty.ticks.template.disabled = true;\r\n");
      out.write("         \r\n");
      out.write("         series_pty.slices.template.cornerRadius = 10;\r\n");
      out.write("         series_pty.slices.template.innerCornerRadius = 7;\r\n");
      out.write("         series_pty.slices.template.draggable = false;\r\n");
      out.write("         series_pty.slices.template.inert = false;\r\n");
      out.write("         series_pty.alignLabels = false;\r\n");
      out.write("         \r\n");
      out.write("         series_pty.hiddenState.properties.startAngle = 90;\r\n");
      out.write("         series_pty.hiddenState.properties.endAngle = 90;\r\n");
      out.write("         \r\n");
      out.write("         var label_pty = chart_pty.seriesContainer.createChild(am4core.Label);\r\n");
      out.write("         label_pty.textAlign = \"middle\";\r\n");
      out.write("         label_pty.horizontalCenter = \"middle\";\r\n");
      out.write("         label_pty.verticalCenter = \"middle\";\r\n");
      out.write("         label_pty.adapter.add(\"text\", function(text, target){\r\n");
      out.write("           return \"[font-size:1.1em]한달 간[/]\\n[bold font-size:1.3em]강수일수[/]\";\r\n");
      out.write("         })\r\n");
      out.write("         }); \r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("      /** \r\n");
      out.write("      * Line Chart\r\n");
      out.write("      */\r\n");
      out.write("       \r\n");
      out.write("      //---최고기온 데이터 시각화---\r\n");
      out.write("      var tmxChart = new Chart(tmx,\r\n");
      out.write("            {\r\n");
      out.write("               type : 'line',\r\n");
      out.write("               data : {\r\n");
      out.write("                  labels : daydata,\r\n");
      out.write("                  datasets : [{\r\n");
      out.write("                     label : '최고기온',\r\n");
      out.write("                     data : tmxdata,\r\n");
      out.write("                     fill : false,\r\n");
      out.write("                     borderColor : 'rgba(255, 56, 96, 0.5)',\r\n");
      out.write("                     tension : 0.1\r\n");
      out.write("                  }\r\n");
      out.write("\r\n");
      out.write("                  ]\r\n");
      out.write("               },\r\n");
      out.write("               options : {\r\n");
      out.write("                  scales : {\r\n");
      out.write("                     yAxes : [ {\r\n");
      out.write("                        ticks : {\r\n");
      out.write("                           beginAtZero : false,\r\n");
      out.write("                           max:40,\r\n");
      out.write("                           min:15\r\n");
      out.write("                        }\r\n");
      out.write("                     } ]\r\n");
      out.write("                  }\r\n");
      out.write("               }\r\n");
      out.write("            });\r\n");
      out.write("      \r\n");
      out.write("      //---최저기온 데이터 시각화---\r\n");
      out.write("      var tmnChart = new Chart(tmn,\r\n");
      out.write("            {\r\n");
      out.write("               type : 'line',\r\n");
      out.write("               data : {\r\n");
      out.write("                  labels : daydata,\r\n");
      out.write("                  datasets : [ {\r\n");
      out.write("                     label : '최저기온',\r\n");
      out.write("                     data : tmndata,\r\n");
      out.write("                     fill : false,\r\n");
      out.write("                     borderColor : 'rgba(50, 115, 220, 0.5)',\r\n");
      out.write("                     tension : 0.1\r\n");
      out.write("                  }\r\n");
      out.write("\r\n");
      out.write("                  ]\r\n");
      out.write("               },\r\n");
      out.write("               options : {\r\n");
      out.write("                  scales : {\r\n");
      out.write("                     yAxes : [ {\r\n");
      out.write("                        ticks : {\r\n");
      out.write("                           beginAtZero : false,\r\n");
      out.write("                           max:40,\r\n");
      out.write("                           min:15\r\n");
      out.write("                        }\r\n");
      out.write("                     } ]\r\n");
      out.write("                  }\r\n");
      out.write("               }\r\n");
      out.write("            });\r\n");
      out.write("   </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
